### ISSUE TITLE
Cannot read property 'selections' of null

### ISSUE THREAD

**Issue by dustinfarris** [mattkrick/cashay#131]
I am bumping in to this error at this line: https://github.com/mattkrick/cashay/blob/8d9174d478b63883f68b64f82c183b60a3aad0c4/src/normalize/denormalizeStore.js#L34

This started happening after I added a custom type to my schema.  When i had "hello" resolving to "world" everything worked fine, but when i tried to create a very basic "user" type, i started seeing this.

I'm not sure what's going on here, could use a point in the right direction.

**Comment by mattkrick** [comment]
thanks for the bug report! Can you share your schema & query? If not everything, at least the part where it gets tripped up.

**Comment by dustinfarris** [comment]
Sure!

This is my schema.js which contains everything.

(Note that this is a function because of how I handle importing and passing around graphql)

```js
// graphql/server/schema.js

export default function(graphql) {
  const {
    GraphQLSchema,
    GraphQLObjectType,
    GraphQLString,
    GraphQLNonNull,
    GraphQLID
  } = graphql;

  const User = new GraphQLObjectType({
    name: 'User',
    description: 'Stuff',
    fields: () => ({
      id: {
        type: GraphQLID,
        description: 'the id'
      },
      name: {
        type: GraphQLString,
        description: 'the name'
      }
    })
  });

  const queryType = new GraphQLObjectType({
    name: 'RootQueryType',
    fields: () => ({
      hello: {
        type: GraphQLString,
        resolve() {
          return 'world';
        }
      },
      user: {
        type: User
      }
    })
  });

  return new GraphQLSchema({
    query: queryType
  });
}
```

**Comment by dustinfarris** [comment]
Also, the error gets triggered when I run ```cashay.query(`{ user }`)```

Running ```cashay.query(`{ hello }`)``` works fine.

**Comment by dustinfarris** [comment]
Updated example with a resolve callback.  Still getting the same error.

**Comment by dustinfarris** [comment]
@mattkrick any idea what might be causing this error?  i am not too knowledgable on how ASTs work or what exactly is being done by the offending line, but i want to help!

**Comment by mattkrick** [comment]
AH! Sorry I replied a few days ago but guess it didn't make it to github. Thanks for the ping!
I think the cause is that you're returning a string instead of a document (complete with an id field). I'll fix this

**Comment by mattkrick** [comment]
okie doke, so the problem is that your query isn't valid. GraphQL is super declarative, so you'd need to write:
```
user {
  id
  name 
}
```

Otherwise, it doesn't know what fields to grab for ya. 

That said, Cashay should probably throw up a useful warning message. I'll fix that

**Comment by dustinfarris** [comment]
Thanks for the quick feedback.  I'll give it a try later today.

**Comment by dustinfarris** [comment]
Adding the fields works.  Thanks!

FYI, if the `id` field is omitted, I get this error:

```
Uncaught TypeError: Cannot read property 'find' of undefined
```

occurring at this line:

https://github.com/mattkrick/cashay/blob/master/src/normalize/normalizeResponse.js#L52

maybe this needs a friendlier error as well?

**Comment by mattkrick** [comment]
that sounds good, i'll add that to the PR

**Comment by dustinfarris** [comment]
Awesome!  Thanks for the quick feedback.  I'll make the adjustment, and close after I verify.

**Comment by mattkrick** [comment]
Ah, you know what, I don't think I planned for any query from the root
query to return a primitive. Usually a query returns a document that
includes an ID field. If you don't have an ID, then it can't really cache
it efficiently. I'll dig in and see if I can reproduce.
