### ISSUE TITLE
Wires crossed with CachedQuery data objects

### ISSUE THREAD

**Issue by dustinfarris** [mattkrick/cashay#144]
I am running into a strange scenario where the data in a cached query looks like (but is oddly not an instance of) Ember.Object.  It has getters and setters and meta properties just like an Ember.Object.  I am noticing this specifically in the mutation handler `currentResponse` param:

![](https://www.dropbox.com/s/xhhz7jddqpo2chc/Screenshot%202016-12-04%2017.04.16.png?dl=1)

CachedQuery objects are internal to cashay so I am astonished that I am seeing something that looks like Ember.Object.

I am investigating where this overlap is occurring.  I assume the problem is on my end, but I noticed [this line in the action project](https://github.com/ParabolInc/action/blob/47e3310bd14b9896ab163e19dc0731d23cd61aaf/src/universal/modules/summary/containers/MeetingSummary/MeetingSummaryContainer.js#L46) which made me think there might be a larger issue here.

**Comment by mattkrick** [comment]
That's really weird! I can't comment since cashay doesn't do any ember
stuff but I'd you figure it out lemme know

**Comment by dustinfarris** [comment]
I think I figured this out.

In my `stateToComputed` (our version of `stateToProps` in react-redux), I do this:

```js
stateToComputed = (state, { projectId }) => {
  const { data: { project } } = cashay.query(projectQuery, { variables: { projectId } });
}
```

**Comment by dustinfarris** [comment]
I think I figured this out.

In my `stateToComputed` (our version of `stateToProps` in react-redux), I do this:

```js
stateToComputed = (state, { projectId }) => {
  const { data: { project } } = cashay.query(projectQuery, { variables: { projectId } });
  return { project };
}
```

With `project` now available as a computed property, I can use it in the template:

```hbs
{{project-detail project=project}}
```

As soon as I pass it as an attr to another component like this, Ember "binds" it which involves transforming the `project` object into one that signals Ember whenever it changes.  It does this by adding meta data, adding getters and setters—basically hi-jacking the POJO.  _This affects redux state!_

It seems the only way around this is to _deep copy_ the data before returning it in stateToComputed, e.g.:

```js
  const { data: { project } } = cashay.query(projectQuery, { variables: { projectId } });
  return {
    project: jQuery.extend(true, {}, project)
  };
```

I am going to open an issue in ember-redux to address this.

**Comment by mattkrick** [comment]
oh wow, i didn't know ember worked like that! yeah, the redux state should be immutable, so if ember is going to try & mutate it, you'll wanna put something between the redux state & the view layer, otherwise you'll end up having to deep copy an object on every re-render which will get expensive.
