### ISSUE TITLE
Drop graphql

### ISSUE THREAD

**Issue by dustinfarris** [mattkrick/cashay#148]
Leaving this as a placeholder.  I plan on attempting this eventually, if no one does it first.

**Comment by dustinfarris** [comment]
@mattkrick do you have any further thought on this?  from a previous note,

 > Currently, aside from a handful of string constants, cashay just uses parse and print.

The constants are easy enough to copy, but [print](https://github.com/graphql/graphql-js/blob/master/src/language/printer.js) is more involved, and [parse](https://github.com/graphql/graphql-js/blob/master/src/language/parser.js) even more so.

**Comment by mattkrick** [comment]
the naive approach would basically be a cut n paste of both of those functions & deps + string constraints. it'll basically be the entire /language folder of graphql. 

the smarter way would be to build cashay via webpack & perform tree shaking there. that way, the cashay bundle would only include the pieces of graphql that it needed. you could output 2 files (commonjs/umd) if needed. http://www.2ality.com/2015/12/webpack-tree-shaking.html

**Comment by dustinfarris** [comment]
ok, using webpack now (just for cashay/graphql) — thanks for the link
