### ISSUE TITLE
Use introspection instead of or in addition to a schema file

### ISSUE THREAD

**Issue by ksmth** [mattkrick/cashay#28]
Instead of reading a file, it'd be handy if you could provide a graphql endpoint URL instead.

```
import { introspecitonQuery, buildClientSchema } from 'graphql/utilities';

fetch(graphqlURL, {
  method: 'POST',
  body: GraphQLUtilities.introspectionQuery
})
  .then(response => response.json())
  .then(buildClientSchema)
  .then(schema => /* do what you do now with the schema */);
```

what do you think?

**Comment by mattkrick** [comment]
nice, i never thought of that, but it makes perfect sense! Seems like this would play nicely with things like GraphQLHub so you don't need to download the server schema. Any ideas on how to keep it up to date? Would you just cronjob it?
i'm assuming `graphql/utilities` should be replaced with `cashay/utilities`?

**Comment by ksmth** [comment]
There's no need to replace `graphql/utilities`, they are documented here:
http://graphql.org/docs/api-reference-utilities/

I wouldn't cronjob it, I'd make it part of the `updateSchema.js`. Instead of:
```
node ./node_modules/cashay/updateSchema.js ./schema.js ./clientSchema.js
```

You would do:
```
node ./node_modules/cashay/updateSchema.js https://example.com/graphql ./clientSchema.js
```

**Comment by mattkrick** [comment]
right, but how often would you run it? How will you know when a 3rd party server-side schema is updated?

**Comment by dahjelle** [comment]
Sometimes, it'd be nice to update the schema every time someone loaded your app—or even provide a hook to tell `cashay` when the server-side schema has been updated. Some reasons it could change: server-side upgrades or dynamic schemas (such as for providing user-customizable fields or even a complete database app).

I haven't dug in enough to know what you are using the schema for or how you are including the file (i.e. during a webpack build or via `fetch` or whatever), so I'm likely completely out of touch as to what makes sense for `cashay`. Just sharing some use-cases I've run in to. :-)
