### ISSUE TITLE
pagination

### ISSUE THREAD

**Issue by mattkrick** [mattkrick/cashay#4]
graphql has no concept of pagination, to it, it's just a bunch of normal everyday args.
cashay should be opinionated, yet DB agnostic.
RethinkDB offers 3 recipes: https://www.rethinkdb.com/docs/cookbook/javascript/#pagination

- skip and limit (good)
- slice and limit (better)
- between and limit (best, uses secondary index)

To achieve a between and limit, we'll need:

- an array of args, which will be a superset of the `orderBy` args.
- a document ID for a cursor cursor (defined as `after` or `before`)
- a limit (defined as `first` or `last`)

cashay needs to treat pagination as a child of the query args.
eg  2 queries:

- query 1 is for 1 food articles that isn't expired ordered by expiration date, skipping the first 3
- query 2 is for 2 food articles that isn't expired *reverse* ordered by expiration date, skipping the last 2

```javascript
{
  // args = {expired, orderBy, first, last, after, before} the last 4 are removed from the keys 
  // since they are reserved pagination words 
  getSomeFood: {
    // non-pagination args stored as the map KEY
    "{expired: false, orderBy: 'expirationDate'}": {
      // only used if 'after' or 'first' is an arg
      front: [undefined, undefined, undefined, 'cheese123'],
      // only used if 'before' or 'last' is an arg
      back: [undefined, undefined, 'noodles22', 'cheese123'],
      // when front & back converge, they are replaced with a 'full' array & 'hasNextPage' becomes true
      full: [undefined, undefined, undefined, 'cheese123', 'noodles22', undefined, undefined],
    }
  },
  // All food does does not require pagination (since it's ALL)
  getAllFood: {
    "{expired: false, orderBy: 'expirationDate'}": {
      full: ['pizza', 'pie', 'lemons', 'cheese123', 'noodles22', 'queso', 'chorizo']
    }
  },
  // A single item is presented as on object, not an array
  getFirstFoodItem: {
    "noArgs": 'pizza',
    "{expired: true}": 'spaghetti'
  },
  getLastFoodItem: {
    "noArgs": 'chorizo'
  }
}
```
V8 currently starts deoptimizing sparse arrays at 100,000 documents (IIRC), so even a few thousand `undefined`s is OK.

The final step is convergence from front to back. As seen above, item 4 is `cheese123`, which is in both arrays. That means we are guaranteed that there are 7 items total. If we know the item count and cursor, we can easily calculate `hasNextPage` and `hasPreviousPage`. No need to store it.

We could either set a flag like `hasConverged = true` or we could create a new `full` array. I like the new 'full' array idea because otherwise I'd have to create a new array for every fetch, and being immutable, that aint cheap.

for array queries that do not trigger pagination by using the 4 reserved keywords (`before, after, first, last`), results go directly to `full`.

...unless I'm missing something huge where this is gonna make a turd, this is a solid 3.5x easier than how relay works.

**Comment by mattkrick** [comment]
as pointed out by @jeffreywescott, this strategy doesn't allow for starting from anywhere except the beginning or the end (eg "give me results 11-20" is impossible). A fix would be to make `skip` a reserved word as well. The `skip` gets passed to the server & the new array would be padded with that many `undefined`s.

**Comment by mattkrick** [comment]
where this may fall short is if nested fields take args. since its args come from the top, we'd have to refetch the parent even if only the nested field arg is changed. 

```
query getStuff($noteId: !ID, $commentCount: !Int) {
  getNote(id: $noteId) {
    id
    name
    comments(count: $commentCount) {
      id
      body
    }
  }
}
```

What's worse is if both the parent & child use pagination, since this employs reserved words...

**Comment by mattkrick** [comment]
In addition to crummy caching, version 1 didn't allow for a many-to-many relationship between documents and queries. This is necessary because 1 query might paginate based on an 'id' while another may use a timestamp. *This* is why relay needed the graph architecture between queries & documents (or connections and nodes). By storing that edge in a document (or query) it hides the complexity from the developer. If I had control over the cursor creation, I could simply do away with the cursor & just require an `id` and `orderBy` and eliminate this mess. Unfortunately, data will come from 3rd party services like twitter, and not everyone uses the document ID for the cursor.

So, that leaves me with something like this (query, vars, store):

```javascript 
export const fb = `
query getPosts(
  $postInput: PostInput,
  $postLikersCursor: String,
  $postLikersLimit: Int
  $commentOrder: String,
  $commentLimit: Int,
  $commentCursor: String,
	$commentLikersLimit: Int,
	$commentLikersCursor: String,
	$commentLikersExcludeAuthor: Boolean) {
  recentPosts(postInput: $postInput) {
    id,
    title,
    body,
    likers(before: $postLikersCursor, last: $postLikersLimit) {
      id,
      name,
      cursor
    },
    comments(order: $commentOrder, first: $commentLimit, cursor: $commentCursor) {
      id,
      title,
      body,
      cursor
      likers(after: $commentLikersCursor, first: $commentLikersLimit, excludeAuthor: $commentLikersExcludeAuthor) {
        id,
        name,
        cursor
      },
    }
  }
}`
const fbVars = {
  postInput: {
    expired: false // If the input is an object, it's stringified
  },
  postLikersCursor: '23', // A cursor can be an ID
  $postLikersLimit: 2,
  commentOrder: 'createdAt', // A list can be ordered however you like
  commentLimit: 2,
  commentCursor: 1454283680638, // A cursor can be anything else, like a timestamp
  commentLikersLimit: 1,
  commentLikersCursor: null, // Or no cursor at all
  $commentLikersExcludeAuthor: true // If it's not pagination related, it's set as the key
}

const store = {
  entities: {
    Post: {
      '123': {
        id: '123',
        title: 'The one two three',
        body: 'foodat',
        likers: {
          "noArgs": { 
            // all args except for "after, before, first, last, cursor" are set as the key
            // since the cursor points to "before: '23"
            // we'll only grab '22' locally & fetch the rest from the server
            // if the count returned from the server is < limit or limit is undefined,
            // then a new "full" array replaces the back and/or front arrays
            back: ['22', '23'] 
          }
        },
        comments: {
          "{order: 'createdAt'}": {
            front: [undefined, undefined, '33', '34', '35']
          }
        }
      }
    },
    People: {
      '22': {
        id: '22',
        name: 'Jerry',
        // a many-to-many relationship exists between documents & queries
        // stated differently, the cursor for a document depends on the query
        // some queries may use the ID, some may use a timestamp
        // by internally looking up the query within the cursor table, we hide the M:N from the dev
        // while keeping the state relatively static
        cursor: {
          "noArgs": '22'
        }
      },
      '23': {
        id: '23',
        name: 'Jose',
        cursor: {
          "noArgs": '23'
        }
      },
      '41': {
        id: '41',
        name: 'Barry',
        cursor: {
          "{excludeAuthor: true}": {
            '41'
          }
        }
      }
    },
    Comment: {
      '33': {
        id: '33',
        title: 'This could work',
        body: 'I think this is nice',
        cursor: {
          "{order: 'createdAt'}": 1454283680638
        },
        likers: {
          "{commentLikersExcludeAuthor: true}": {
            
          }
        }
      }
    }
  },
  rootCallMap: {
    "recentPosts({expired: false})": {
      complete: ['123', '456'] // we know to look in Post thanks to the AST
    }
  }
}
```

**Comment by mattkrick** [comment]
@Bartekus  @jondubois See any reason why storing data in a shape like `sampleStore` below wouldn't work? I'm looking for the edgiest of edge cases

```
const sampleQuery = `query getPosts($postCursor: String, $postLimit: Int) {
  recentPosts(after: $postCursor, first: $postLimit) {
    id,
    title,
    cursor
  }
}`

const sampleVars = {
  postCursor: null,
  postLimit: 2
}

const sampleResponse = {
  data: {
    recentPosts: [
      {
        id: '1',
        title: 'post #1',
        cursor: '1'
      },
      {
        id: '2',
        title: 'post #2',
        cursor: '2'
      },
    ]
  }
}

// HELP ME. Is there any problem with storing info normalized like this?
const sampleStore = {
  entities: {
    Post: {
      '1': {
        id: '1',
        title: 'post #1',
        cursor: {
          "noArgs": '1'
        }
      },
      '2': {
        id: '2',
        title: 'post #2',
        cursor: {
          "noArgs": '2'
        }
      }
    }
  },
  rootCallMap: {
    recentPosts: {
      "noArgs": {
        full: ['1','2']
      }
    }
  }
}
```

**Comment by Bartekus** [comment]
I can't guarantee (I need to sleep on it so to speak), however nothing immediately jumps at me that would suggest that it would not work. It seems quite feasible, but I'll need to familiarize myself with the relay to get a proper context, otherwise my pov is not wide enough to be of practical use.

**Comment by mattkrick** [comment]
aside from the cursor, a relay `connection` also has `hasNextPage, hasPreviousPage`. In the current spec, these are brittle, to say the least. I think the *right* way to do it is to trust that the developer handles it intelligently. that means on the server, the developer queries for eg `first + 1`. If the DB returns < `first + 1` we know that `hasNextPage` is false. Whether they send that extra doc to the client is up to them. 
They have 2 options:
- Replace that doc with an "undefined" and send it down the wire
- Send the full extra doc down the wire
While the 1st saves bandwidth, the 2nd allows for a *really* fancy UI. For example, if the user requests 10 docs in an infinite scroll, you could have the 11th be lightly faded gradient so the user doesn't see all of it & that intuitively tells them to scroll down to fetch more. When the fetch occurs, you could animate the unfading, which provides **instant** feedback to the UI, essentially distracting them for 300-500ms, which is just long enough to make the roundtrip fetch.
If you wanted to get really fancy, you could store the average roundtrip time in the localStore & use that to determine how long to animate the unfading. You can tell I'm stoked on this idea. It drives perceived latency towards 0.

**Comment by mattkrick** [comment]
Another assumption pagination makes is that `(Type, args) => cursor`, which means that given a Type and a list of 0 or more args (excluding `before, after, first, last`) the same document cursor must be returned. I can't think of a single good reason why this would be violated, but it's worth mentioning in case someone finds one.

**Comment by mattkrick** [comment]
merge with #13
