### ISSUE TITLE
Cashay

### ISSUE THREAD

**Issue by jordanh** [mattkrick/cashay#41]
Hi!

When moving [Action](https://github.com/ParabolInc/action/) over to Cashay, we noticed `updateSchema.js` never exits. We using `rethinkdbdash` and it (annoyingly) creates a connection pool we must drain before it will allow the node process to exit. Could we have `updateSchema.js` call a callback when its finished with its work? _A la:_

From:

```bash
$ ./node_modules/.bin/babel-node node_modules/cashay/updateSchema.js src/server/graphql/rootSchema.js build/graphqlSchema.json
```

To: 

```bash
$ ./node_modules/.bin/babel-node node_modules/cashay/updateSchema.js src/server/database/rethinkExit.js src/server/graphql/rootSchema.js build/graphqlSchema.json 
```

Or similar?

**Comment by mattkrick** [comment]
fixed in 0.5.0
