### ISSUE TITLE
Consider a `setTransport` method on the singleton

### ISSUE THREAD

**Issue by mattkrick** [mattkrick/cashay#59]
The singleton is usually created where the store is.
That singleton may need authentication for its transport, eg
```
headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${authToken}`
      }
```
The user may not have that `authToken` yet, as they'll have to log in to get the token.
When they log in, they'll get a token, but the `transport` won't have it, so we'll have to replace the old transport with the new.
Today, we can do that like `cashay.transport = new MyTransport()`.
That's not bad, but it seems kinda hacky since that property isn't explicit in the API.
At the cost of making the API bigger, I could add a method, 
eg `cashay.setTransport(new MyTransport())`.

Side note: Internally, the mutation's `refetch` call will need to call `this.getTransport()` instead of `this.transport` so the stale one can be GC'd away.

Thoughts? @jordanh @simenbrekken

**Comment by jordanh** [comment]
I'm a big fan of explicitness in general. This includes getters and setters. LGTM!

**Comment by mattkrick** [comment]
Alternatively, someone could feed a getter in as their auth token: `() => localStorage.getItem('authToken')`, but there's 2 reasons i like `setTransport` better:
1. You may want to switch from HTTP to socket transport  (in the future...where you actually have that option)
2. localStorage isn't slow, but it ain't fast either. A goal of cashay is to be the cache of choice for 60fps web experiences.
