### ISSUE TITLE
Consider making `cashay.mutation` return a promise

### ISSUE THREAD

**Issue by mattkrick** [mattkrick/cashay#60]
It's possible that we may want to trigger a side effect after a mutation returns.
Normally, I'd suggest listening for the difference in the redux state tree, *but a mutation doesn't guarantee a change to the redux state*. So, there's no real way to know if the server call every returned. However, it *does* guarantee a server call. So, if `cashay.mutate` returns a promise, we can do fun things like redirect, or write to localStorage, etc.

This flexibility gets dangerous since folks would be able to write anti-patterns (eg query after a mutation completes instead of in the mSTP) but that's a documentation problem.

If we accept that a promise has to be returned, should a GraphQL error be a promise rejection?

Side note: the promise will probably have to resolve before calling `dispatch` since the dispatch will likely re-render the component it was called from.

**Comment by jordanh** [comment]
This is so @mattkrick. This will save folks from having to write mutations which mutate remote state just to mutate local state. I think this is a step forward. 👍
